name: build-docs

on:
  push:
    branches:
      - master
      - docs-dev
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"
      - "pyproject.toml"
      - "zabbix_cli/**"

concurrency:
  group: docs-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Install hatch
        run: |
          uv pip install --system hatch

      - name: Build documentation and publish
        run: hatch run docs:mkdocs gh-deploy --force
